# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd9254d6a162e5f39e9214348efa69e6396a43595babc0b1736ba37e051b491cd3d1d3d308faf658313c39f25a70777e123c154a0538529e77a51881e7de1161

test:
  secret_key_base: 44038f82a5cf12f76b6db16473248b351530e43169b7e314f2d2b16624b779cf4ce388048da8069f4576c1699d26c756434d860e45c91dcd1ffc7b6ebe8934ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
